### ISSUE TITLE
Sidecar rewrite.

### ISSUE THREAD

**Issue by misohu** [canonical/kubeflow-volumes-operator#124]
### Context

We rewrite all of our charms using the sidecar with base charm pattern instead of the old podspec.

### What needs to get done

Rewrite the charm using sidecar with base charm pattern. 

### Definition of Done

Charm is rewritten with sidecar with base charm pattern. 
All of the tests are rewritten and passing.

**Comment by ca-scribner** [comment]
Should this be closed by #125?
