### ISSUE TITLE
Integrate the filebrowser rock into `main` and `track/1.8`

### ISSUE THREAD

**Issue by ca-scribner** [canonical/kubeflow-volumes-operator#126]
### Context

canonical/kubeflow-rocks#72 builds and publishes a rock for the filebrowser that is used by kubeflow-volumes.  This rock should be integrated into the charm and pushed to `main` and `track/1.8`

Testing note: at time of writing, to test the volumes webapp UI you need to deploy the full kubeflow bundle as we have not defined a minimum bundle that makes volumes function properly.  Deploying what the integration CI deploys here is not enough

### What needs to get done

1. integrate the rock and test the charm

### Definition of Done

1. charm using the rock is in `main` and `track/1.8`
2. charm using the rock is published to latest/edge and 1.8/edge

**Comment by orfeas-k** [comment]
Closed by #127 and #128.
