### ISSUE TITLE
Do integration tests need istio?

### ISSUE THREAD

**Issue by ca-scribner** [canonical/kubeflow-volumes-operator#18]
Is it possible to decouple the integration tests here from istio and the gateway?  Does volumes need istio to function or is it used for routing the selenium tests?  Couldn't they go directly at the dashboard?  The dashboard operator CI does not use istio

**Comment by DomFleischmann** [comment]
The reason istio was added was that without it the namespace field during the creation of a volume would not be filled as it takes it directly from the user-id which is added in the routing using istio.

There might be a way of avoiding this but at the time I ran out of time and stuck with adding istio.

**Comment by DomFleischmann** [comment]
Closing this for now, we are currently testing our UIs with istio, if we want to change that we need to address it on a bigger level.
